- name: install packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - qemu-kvm
    - bridge-utils
    - libvirt-python

- name: download
  get_url:
    url: http://ftp.jaist.ac.jp/pub/Linux/CentOS/7/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso
    dest: /home/{{ user }}/centos7.iso

